version: "3.0"

services:
  arango1:
    image: arangodb/arangodb:3.10.0
    ports:
      - "8529:8529"
    volumes:
      - arango1:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: tremors
    command: arangodb --starter.join arango1,arango2,arango3
  arango2:
    image: arangodb/arangodb:3.10.0
    ports:
      - "8530:8529"
    volumes:
      - arango2:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: tremors
    command: arangodb --starter.join arango1,arango2,arango3
  arango3:
    image: arangodb/arangodb:3.10.0
    ports:
      - "8531:8529"
    volumes:
      - arango2:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: tremors
    command: arangodb --starter.join arango1,arango2,arango3
volumes:
  arango1:
  arango2:
  arango3: