#!/bin/sh

echo "Please, install cbor-tool."
echo "Removing old cbor files."

for file in *.cbor 
do
  [ -e "$file" ] || continue
  rm $file
done

for json in *.json
do

  echo "Writing a new cbor for $json."
  cbor-tool encode --json $json
done



