version: "3.0"

services:

  arango:
    image: docker.io/library/arangodb:3.11.0
    environment:
      ARANGO_ROOT_PASSWORD: tremors
    ports:
      - "8529:8529"

  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:6.1.9
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: docker.io/confluentinc/cp-kafka:6.1.9
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://rthoth.local:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  graboid:
    image: docker.io/estrondo-tremors:graboid-latest
    environment:
      TREMORS_PROFILE: local

  toph:
    image: docker.io/estrondo-tremors:toph-latest
    environment:
      TREMORS_PROFILE: local
    ports:
      - "9443:9443"