version: "3.9"

services:
  arango1:
    image: docker.io/arangodb/arangodb:3.10.0
    ports:
      - "8529:8529"
    volumes:
      - arango1:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: tremors
    command: arangodb --starter.address=arango1
  arango2:
    image: docker.io/arangodb/arangodb:3.10.0
    ports:
      - "8530:8529"
    volumes:
      - arango2:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: tremors
    command: arangodb --starter.address=arango2 --starter.join arango1
  arango3:
    image: docker.io/arangodb/arangodb:3.10.0
    ports:
      - "8531:8529"
    volumes:
      - arango3:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: tremors
    command: arangodb --starter.address=arango3 --starter.join arango1

  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper:6.1.9
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: docker.io/confluentinc/cp-kafka:6.1.9
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://rthoth.local:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka2:
    image: docker.io/confluentinc/cp-kafka:6.1.9
    depends_on:
      - zookeeper
    ports:
      - "9094:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL://rthoth.local:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zkcmak:
    image: docker.io/confluentinc/cp-zookeeper:6.1.9
    restart: always
    environment:
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  cmak:
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5
    depends_on:
      - zkcmak
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zkcmak:2181"

  graboid:
    image: docker.io/rthoth/estrondo:graboid
    environment:
      TREMORS_PROFILE: dev
      GRABOID_ARANGO_DATABASE: graboid
      GRABOID_ARANGO_USERNAME: root
      GRABOID_ARANGO_PASSWORD: tremors
      GRABOID_ARANGO_HOSTS: arango1:8529,arango2:8529,arango3:8529
      GRABOID_KAFKA_CLIENT_ID: graboid
      GRABOID_KAFKA_CLOSE_TIMEOUT: 10 seconds
      GRABOID_KAFKA_BOOTSTRAP: PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9092

  toph:
    image: docker.io/rthoth/estrondo:toph
    ports:
      - "9000:9000"
    environment:
      TREMORS_PROFILE: dev
      TOPH_ARANGO_DATABASE: toph
      TOPH_ARANGO_USERNAME: root
      TOPH_ARANGO_PASSWORD: tremors
      TOPH_ARANGO_HOSTS: arango1:8529,arango2:8529,arango3:8529
      TOPH_KAFKA_CLIENT_ID: graboid
      TOPH_KAFKA_CLOSE_TIMEOUT: 10 seconds
      TOPH_KAFKA_BOOTSTRAP: PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9092
      TOPH_GRPC_PORT: 9000
volumes:
  arango1:
  arango2:
  arango3:
